name: tests

on:
  push:
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run Pint (code style)
        run: composer format -- --test

      - name: Run tests
        run: composer test
